/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionemtrafesa.capa1_presentacion;

import aplicacionemtrafesa.capa1_presentacion.util.Mensaje;
import aplicacionemtrafesa.capa2_aplicacion.GestionarRutaServicio;
import aplicacionemtrafesa.capa3_Dominio.Entidades.Ruta;
import javax.swing.JDialog;

/**
 *
 * @author Home
 */
public class FormDatosRuta extends javax.swing.JDialog {

    private final int ACCION_CREAR = 1;
    private final int ACCION_MODIFICAR = 2;
    private int tipo_accion;
    private Ruta ruta;
    
    public FormDatosRuta(JDialog owner) {
        super(owner, true);
        initComponents();
        tipo_accion = ACCION_CREAR;
        this.ruta = new Ruta();
        
    }
    public FormDatosRuta(JDialog owner, Ruta ruta) {
        super(owner, true);
        initComponents();
        tipo_accion = ACCION_MODIFICAR;
        this.ruta = new Ruta();
        txtOrigen.setText(ruta.getOrigen());
        txtDestino.setText(ruta.getDestino());
        txtPrecio.setText(String.valueOf(ruta.getPrecio()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Datos de la Ruta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setText("Origen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, -1));

        jLabel2.setText("Destino");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        getContentPane().add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, -1));

        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ruta.setOrigen(txtOrigen.getText());
        ruta.setDestino(txtDestino.getText());
        ruta.setPrecio(Double.parseDouble(txtPrecio.getText()));
        GestionarRutaServicio gestionarRutaServicio = new GestionarRutaServicio();
        int registros_afectados;
        if(tipo_accion == ACCION_CREAR){
            try{
                registros_afectados = gestionarRutaServicio.crearRuta(ruta);
                if(registros_afectados == 1){
                    Mensaje.mostrarAfirmacionDeCreacion(this);
                    this.dispose();
                }
                else 
                    Mensaje.mostrarAdvertenciaDeCreacion(this);
            }catch(Exception e){
                Mensaje.mostrarErrorDeCreacion(this);
            }
        }
        else{
            try{
                registros_afectados = gestionarRutaServicio.modificarRuta(ruta);
                if(registros_afectados == 1){
                    Mensaje.mostrarAfirmacionDeActualizacion(this);
                    this.dispose();
                }
                else
                    Mensaje.mostrarAdvertenciaDeActualizacion(this);
            }catch(Exception e){
                Mensaje.mostrarErrorDeActualizacion(this);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtOrigen.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
