/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionemtrafesa.capa1_presentacion;

import aplicacionemtrafesa.capa1_presentacion.util.ConfiguradorDeTabla;
import aplicacionemtrafesa.capa1_presentacion.util.Mensaje;
import aplicacionemtrafesa.capa2_aplicacion.GestionarRutaServicio;
import aplicacionemtrafesa.capa3_Dominio.Entidades.Ruta;
import java.util.List;
import javax.swing.JDialog;
import mastersoft.modelo.ModeloTabla;
import mastersoft.tabladatos.Columna;
import mastersoft.tabladatos.Fila;
import mastersoft.tabladatos.Tabla;

/**
 *
 * @author Home
 */
public class FormGestionarRuta extends javax.swing.JDialog {

    private void crearTabla(){
        Tabla tabla = new Tabla();
        tabla.agregarColumna(new Columna("ID","java.lang.Integer"));
        tabla.agregarColumna(new Columna("Origen", "java.lang.String"));
        tabla.agregarColumna(new Columna("Destino","java.lang.String"));
        tabla.agregarColumna(new Columna("Precio","java.lang.Double"));
        ModeloTabla modeloTabla = new ModeloTabla(tabla);
        tablaRutas.setModel(modeloTabla);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaRutas, 1, 250, 400, 50);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaRutas, 2, 80, 100, 50);
        ConfiguradorDeTabla.configurarAnchoColumna(tablaRutas, 3, 80, 100, 50);
        ConfiguradorDeTabla.ocultarColumna(tablaRutas, 0);
    }
    public FormGestionarRuta(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        crearTabla();
        txtBuscar.requestFocusInWindow();
    }

    private void buscar(){
        Fila filaTabla;
        String buscar = txtBuscar.getText().trim();
        try{
            GestionarRutaServicio gestionarRutaServicio = new GestionarRutaServicio();
            List<Ruta> rutas = gestionarRutaServicio.buscarRutas(buscar);
            ModeloTabla modeloTabla = (ModeloTabla)tablaRutas.getModel();
            modeloTabla.eliminarTotalFilas();
            for(Ruta ruta : rutas){
                filaTabla = new Fila();
                filaTabla.agregarValorCelda(ruta.getRutaID());
                filaTabla.agregarValorCelda(ruta.getOrigen());
                filaTabla.agregarValorCelda(ruta.getDestino());
                filaTabla.agregarValorCelda(ruta.getPrecio());
                modeloTabla.agregarFila(filaTabla);
            }
            modeloTabla.refrescarDatos();
        }catch(Exception e){
            Mensaje.mostrarErrorDeConsulta(this);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        botCrear = new javax.swing.JMenu();
        botModificar = new javax.swing.JMenu();
        botEliminar = new javax.swing.JMenu();
        botSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 52, -1, -1));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, -1));

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaRutas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 430, 270));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        botCrear.setText("Crear");
        botCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botCrearMouseClicked(evt);
            }
        });
        jMenuBar1.add(botCrear);

        botModificar.setText("Modificar");
        jMenuBar1.add(botModificar);

        botEliminar.setText("Eliminar");
        jMenuBar1.add(botEliminar);

        botSalir.setText("Salir");
        botSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(botSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botSalirMouseClicked
        this.dispose();
        new FormMenu().setVisible(true);
    }//GEN-LAST:event_botSalirMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void botCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCrearMouseClicked
        FormDatosRuta formDatosRuta = new FormDatosRuta(this);
        formDatosRuta.setVisible(true);
        buscar();
    }//GEN-LAST:event_botCrearMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botCrear;
    private javax.swing.JMenu botEliminar;
    private javax.swing.JMenu botModificar;
    private javax.swing.JMenu botSalir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
