/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionemtrafesa.capa1_presentacion;

import javax.swing.JDialog;

/**
 *
 * @author Home
 */
public class FormGestionarRuta extends javax.swing.JDialog {

    private void crearTabla(){
        Tabla tabla = new Tabla();
        
    }
    public FormGestionarRuta(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        botCrear = new javax.swing.JMenu();
        botModificar = new javax.swing.JMenu();
        botEliminar = new javax.swing.JMenu();
        botSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 52, -1, -1));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, -1));

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaRutas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 430, 270));

        botCrear.setText("Crear");
        jMenuBar1.add(botCrear);

        botModificar.setText("Modificar");
        jMenuBar1.add(botModificar);

        botEliminar.setText("Eliminar");
        jMenuBar1.add(botEliminar);

        botSalir.setText("Salir");
        botSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(botSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botSalirMouseClicked
        this.dispose();
        new FormMenu().setVisible(true);
    }//GEN-LAST:event_botSalirMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botCrear;
    private javax.swing.JMenu botEliminar;
    private javax.swing.JMenu botModificar;
    private javax.swing.JMenu botSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
